name: Github Action Demo
on: [push]
jobs:
  Github-Action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@4
      - name: Print index.html file
        runs: cat index.html
